### ISSUE TITLE
Post a deprecation in the README

### ISSUE THREAD

**Issue by shamilovtim** [react-native-linear-gradient/react-native-linear-gradient#528]
Given the efforts of the Expo team to have modern features like tree shaking and web support it seems that `expo-linear-gradient` supersedes this effort. I would suggest posting a deprecation notice in the README to inform people to migrate!

**Comment by zifahm** [comment]
@shamilovtim  its not like everybody can use unimodules. I use React native navigation so unimodules is a no go for me.
