### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by EKT2000** [react-native-linear-gradient/react-native-linear-gradient#564]
Hi, I had an error while updating my app to 0.66.2. After updating all the react native dependencies, I get following error on npm install:

```
Found: react@17.0.2
node_modules/react
     react@"17.0.2" from the root project

Could not resolve dependency:
peer react@"^16.8.1" from react-native-linear-gradient@2.6.0
node_modules/react-native-linear-gradient
    react-native-linera-gradient@"^2.6.0" from the root project

```

Any Ideas on how to solve that?

**Comment by friederbluemle** [comment]
Thanks for the report @EKT2000 and thanks for the quick fix @aminmahrami :+1:

2.6.1 is available which should fix the error.
