### ISSUE TITLE
missing types on 2.7.x

### ISSUE THREAD

**Issue by efstathiosntonas** [react-native-linear-gradient/react-native-linear-gradient#609]
The types are missing from the today's releases `2.7.x`

![Screenshot 2023-06-15 at 16 29 58](https://github.com/react-native-linear-gradient/react-native-linear-gradient/assets/717975/22af9664-ca73-4a33-a100-4a4314986b88)

**Comment by friederbluemle** [comment]
Please try again using version `2.7.2`.
