### ISSUE TITLE
error: cannot find symbol import com.facebook.react.bridge.ColorPropConverter

### ISSUE THREAD

**Issue by aurangs7** [react-native-linear-gradient/react-native-linear-gradient#616]
Getting build error in Android: 

My env:
**"react-native": "^0.61.5", (Not able to update because of some dependencies)
"react-native-linear-gradient": "^2.7.3",**

`error: cannot find symbol
import com.facebook.react.bridge.ColorPropConverter;
                                ^
  symbol:   class ColorPropConverter
  location: package com.facebook.react.bridge`
  
  
<img width="1060" alt="Screenshot 2023-06-26 at 14 50 21" src="https://github.com/react-native-linear-gradient/react-native-linear-gradient/assets/110371514/ea7ae471-0461-4c02-9cce-cfd2c9caa75e">

**Comment by friederbluemle** [comment]
Hi @aurangs7 - For React Native <0.63 please continue to use `react-native-linear-gradient@^2.6.2`.
Starting with 2.7.0 we require React Native >= 0.63 due to #540
I've updated the release notes for https://github.com/react-native-linear-gradient/react-native-linear-gradient/releases/tag/v2.7.0 to also mention this. Thanks for the report.

**Comment by anadithakur** [comment]
Getting build error in Android:

`/node_modules/react-native-linear-gradient/android/src/main/java/com/BV/LinearGradient/LinearGradientView.java:3: error: cannot find symbol
import com.facebook.react.bridge.ColorPropConverter;
                                ^
  symbol:   class ColorPropConverter
  location: package com.facebook.react.bridge
/node_modules/react-native-linear-gradient/android/src/main/java/com/BV/LinearGradient/LinearGradientView.java:143: error: cannot find symbol
                            ? ColorPropConverter.getColor(colors.getMap(i), getContext())
                              ^
  symbol:   variable ColorPropConverter
  location: class LinearGradientView
2 errors
Task :react-native-linear-gradient:compileReleaseJavaWithJavac in app Finished
:react-native-linear-gradient:compileReleaseJavaWithJavac (Thread[Execution worker for ':',5,main]) completed. Took 0.041 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-linear-gradient:compileReleaseJavaWithJavac'.`

My env:
"react":"16.11.0",
"react-native": "^0.61.3", (Not able to update because of some fixed project guidelines),
"react-native-linear-gradient": "^2.6.2",

**Comment by mschouhan123** [comment]
> Getting build error in Android:
> 
> > /node_modules/react-native-linear-gradient/android/src/main/java/com/BV/LinearGradient/LinearGradientView.java:3: error: cannot find symbol
> > import com.facebook.react.bridge.ColorPropConverter;
> > ^
> > symbol:   class ColorPropConverter
> > location: package com.facebook.react.bridge
> > /node_modules/react-native-linear-gradient/android/src/main/java/com/BV/LinearGradient/LinearGradientView.java:143: error: cannot find symbol
> > ? ColorPropConverter.getColor(colors.getMap(i), getContext())
> > ^
> > symbol:   variable ColorPropConverter
> > location: class LinearGradientView
> > 2 errors
> > Task :react-native-linear-gradient:compileReleaseJavaWithJavac in app Finished
> > :react-native-linear-gradient:compileReleaseJavaWithJavac (Thread[Execution worker for ':',5,main]) completed. Took 0.041 secs.
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   Execution failed for task ':react-native-linear-gradient:compileReleaseJavaWithJavac'.
> 
> My env: "react":"16.11.0", "react-native": "^0.61.3", (Not able to update because of some fixed project guidelines), "react-native-linear-gradient": "^2.6.2",

Getting the Same issue, can anyone help ?

**Comment by anadithakur** [comment]
> Getting build error in Android:
> 
> > /node_modules/react-native-linear-gradient/android/src/main/java/com/BV/LinearGradient/LinearGradientView.java:3: error: cannot find symbol
> > import com.facebook.react.bridge.ColorPropConverter;
> > ^
> > symbol:   class ColorPropConverter
> > location: package com.facebook.react.bridge
> > /node_modules/react-native-linear-gradient/android/src/main/java/com/BV/LinearGradient/LinearGradientView.java:143: error: cannot find symbol
> > ? ColorPropConverter.getColor(colors.getMap(i), getContext())
> > ^
> > symbol:   variable ColorPropConverter
> > location: class LinearGradientView
> > 2 errors
> > Task :react-native-linear-gradient:compileReleaseJavaWithJavac in app Finished
> > :react-native-linear-gradient:compileReleaseJavaWithJavac (Thread[Execution worker for ':',5,main]) completed. Took 0.041 secs.
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   Execution failed for task ':react-native-linear-gradient:compileReleaseJavaWithJavac'.
> 
> My env: "react":"16.11.0", "react-native": "^0.61.3", (Not able to update because of some fixed project guidelines), "react-native-linear-gradient": "^2.6.2",

I have tried downgrading "react-native-linear-gradient" from "2.6.2" to "2.5.6" but still facing same error.
@friederbluemle Help please!!

**Comment by friederbluemle** [comment]
@anadithakur - The build error indicates that you are using 2.7.0+, and not 2.6.2 or 2.5.6
I'd have to take a look at your project to say exactly why that is.
In your previous message you mentioned you declared the dependency like this:
```
"react-native-linear-gradient": "^2.6.2",
```
So my best guess is that you (accidentally?) updated react-native-linear-gradient in your lockfile (or recreated the lockfile with newer versions, or maybe even don't use a lockfile?)

Note that `2.7.x` _also_ falls into the version range of `^2.6.2`.
So once you have 2.7.x in your lockfile, simply changing it to `^2.6.2` or `^2.5.6` in package.json **will not** downgrade the dependency.
What you could try (while you still depend on RN 0.61), is to change the declaration to
```
"react-native-linear-gradient": "~2.6.2",
```
This will ensure the minor part will remain at `6`, while still enabling potential patch updates.

**Comment by hoangittc** [comment]
fix : "react-native-linear-gradient": "2.5.6", (remove "^")

**Comment by friederbluemle** [comment]
@hoangittc - While your answer (also) solves the immediate issue, it comes with another problem: If you _remove_ the caret, it will no longer allow patch updates in the same major.minor version range. For example say there is new security fix released as 2.5.7, an upgrade **would not be able to find** it. Perhaps the bigger issue is that if another dependency _also_ depends on the same package, it might **no longer be able to de-duplicate** the versions.

Please read my answer to understand why a `~` limitation (in case the default `^` is not possible) is preferable over simply removing allowed ranges altogether.

@aurangs7 @mschouhan123 @anadithakur - Could you please confirm whether limiting to the 2.6.x range worked for you? There should be no need to go down to 2.5.x

**Comment by mar10-emil** [comment]
I had the exact same issue and I can confirm `~2.6.2` fixed the issue

**Comment by manssorr** [comment]
> Hi @aurangs7 - For React Native <0.63 please continue to use `react-native-linear-gradient@~2.6.2`. Starting with 2.7.0 we require React Native >= 0.63 due to #540 I've updated the release notes for https://github.com/react-native-linear-gradient/react-native-linear-gradient/releases/tag/v2.7.0 to also mention this. Thanks for the report.

Perfect Solution! Thanks

**Comment by khushbuMk** [comment]
I replaced ^ with ~ to solve this issue. It worked.
