### ISSUE TITLE
Crash on iOS 17 Beta 2 and 3 compiled with iOS 17 SDK

### ISSUE THREAD

**Issue by mwa3aan** [react-native-linear-gradient/react-native-linear-gradient#618]
When running a project that uses react-native-linear-gradient compiled in XCode 15 Beta 3 and iOS 17 Beta 3.

The exception in XCode when running in debug is 
```
reason	__NSCFString *	"UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={0, 0}, scale=3.000000, bitmapInfo=0x2006. Use UIGraphicsImageRenderer to avoid this assert."	0x000060000374f180
```

Looking at the call stack it fails on line 58 when calling UIGraphicsBeginImageContextWithOptions in BVLinearGradientLayer:
```
- (void)display {
    [super display];

    BOOL hasAlpha = NO;

    for (NSInteger i = 0; i < self.colors.count; i++) {
        hasAlpha = hasAlpha || CGColorGetAlpha(self.colors[i].CGColor) < 1.0;
    }

    UIGraphicsBeginImageContextWithOptions(self.bounds.size, !hasAlpha, 0.0);
    CGContextRef ref = UIGraphicsGetCurrentContext();
    [self drawInContext:ref];

    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    self.contents = (__bridge id _Nullable)(image.CGImage);
    self.contentsScale = image.scale;

    UIGraphicsEndImageContext();
}
```

This works on all previous versions of iOS 16, even when running on iOS 17 Beta 3, as long as it is not compiled against the iOS 17SDK.

referring to https://developer.apple.com/documentation/uikit/1623912-uigraphicsbeginimagecontextwitho. Even though UIGraphicsBeginImageContextWithOptions is still available in iOS 17, it is deprecated.

**Comment by mwa3aan** [comment]
It seems like it was an issue in one of our images, but that same image does not crash the app on a native code level when compiled against iOS 16 SDK.

**Comment by JDouven** [comment]
We are also seeing this issue

**Comment by iit2008047** [comment]
any update on this ?

**Comment by relaxxpls** [comment]
Facing this.
@mwa3aan could you kindly explain your case and soln?

**Comment by mwa3aan** [comment]
> Facing this.
> 
> @mwa3aan could you kindly explain your case and soln?

@relaxxpls we had different build profiles and one of the used different image assets that worked. I was traveling with my son and just got back so I haven't looked into it. 

However, with Xcode Beta 5 and the latest iOS beta it works without crashing with all of our build configurations. So something was fixed in either the package or in the latest iOS SDK. 

I hope this helps.

**Comment by mwa3aan** [comment]
@relaxxpls the crash occurs when the resource you try to display isn't available. it tries to render an empty image and crash. seems like previously this failed gracefully under the iOS SK, but now it causes the crash. We made sure that whenever we call the functions in react-native-linear-gradient the image or asset you are using is available and not empty/null.

I hope this helps.

**Comment by mwa3aan** [comment]
#626 fixed the issue above for us!!
