### ISSUE TITLE
Incompatible types: List<LinearGradientManager> cannot be converted to List<ViewManager>

### ISSUE THREAD

**Issue by canhtran10** [react-native-linear-gradient/react-native-linear-gradient#623]
Reactnative: 0.64
Java: 11
----------------------------
I am facing this issue:
node_modules\react-native-linear-gradient\android\src\main\java\com\BV\LinearGradient\LinearGradientPackage.java:23: error: incompatible types: List<LinearGradientManager> cannot be converted to List<ViewManager>
        return Collections.singletonList(new LinearGradientManager());

Just changed it as below works fine, why????:
node_modules/react-native-linear-gradient/android/src/main/java/com/BV/LinearGradient/LinearGradientPackage.java
@NonNull
@Override
public List<ViewManager> createViewManagers(@NonNull ReactApplicationContext reactContext) {
    // return Collections.singletonList(new LinearGradientManager()); //commment this line
    return Collections.<ViewManager>singletonList(new LinearGradientManager()); //add this line
}

I don't know everyone is facing this problem or not?

**Comment by soluelue** [comment]
Hi.
I have a same problem. So, I solved this issue like that.

``` 
@NonNull
@Override
    public List<ViewManager> createViewManagers(@NonNull ReactApplicationContext reactContext) {
        return Collections.singletonList((ViewManager)new LinearGradientManager());
    }
```

**Comment by friederbluemle** [comment]
@canhtran10 - Thank you for the report.

Please check #624 for more details why this is happening and a fix.

A new version 2.8.1 will be out shortly which will fix it - Please update your dependency (cc @soluelue).
