### ISSUE TITLE
Task :react-native-linear-gradient:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by anlun214** [react-native-linear-gradient/react-native-linear-gradient#630]
"react": "18.2.0",
    "react-native": "0.71.7",
    java version 20
    
   I don't know what happened.
   any one can help me.

**Comment by anlun214** [comment]
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Zulu20.30+11-CA (build 20.0.1+9)
OpenJDK 64-Bit Server VM Zulu20.30+11-CA (build 20.0.1+9, mixed mode, sharing)

mac book m2

**Comment by friederbluemle** [comment]
Hi @anlun214
1. Can you copy+paste the full error details (stacktrace) that is printed past `compileDebugJavaWithJavac FAILED`?
2. I don't think Java 20 is officially supported by React Native or Android. The very latest versions of Android Studio just started shipping with Java 17, but for your version of RN, you should probably be on Java 11.

**Comment by ludovic-noirault** [comment]
I have encountered the same thing on a release build.
Downgrading to the 2.8.0 version helped overcome it.

**Comment by friederbluemle** [comment]
@ludovic-noirault - Can you please share the stacktrace if possible?

**Comment by friederbluemle** [comment]
@anlun214 @ludovic-noirault Can you please check if version `2.8.2` fixes the issue for you?

**Comment by ludovic-noirault** [comment]
> @anlun214 @ludovic-noirault Can you please check if version `2.8.2` fixes the issue for you?

Hello,
This new version allows me to build without issues, for both androidTV and tvos
Thanks a lot !

**Comment by friederbluemle** [comment]
Great, thanks for the quick reply. I will close this issue now.

**Comment by kokosky93** [comment]
"react-native-linear-gradient": "~2.8.2",

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-linear-gradient'.
> Could not open cp_proj generic class cache for build file 'C:\Repos\OneYearChallenge\mobile-client\Stormflake\node_modules\react-native-linear-gradient\android\build.gradle' (C:\Users\Wojci\.gradle\caches\7.5.1\scripts\eand01qoikr91y6x08cca6ri2).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

**Comment by hello-sarvesh** [comment]
This error occurs because your JDK version as higher or lower for react-native. to check full issue run ` npx react-native doctor`.
your error like
![Screenshot 2024-04-11 000659](https://github.com/react-native-linear-gradient/react-native-linear-gradient/assets/118502711/f840e97b-5ab7-4074-ad7a-558561d1a9cf)
